directories:
  output: dist-electron
  buildResources: build
appId: com.vila.pos
productName: Vila POS System
files:
  - filter:
      - dist/**/*
      - public/electron.js
      - public/preload.js
      - assets/**/*
      - node_modules/**/*
win:
  target: nsis
  icon: assets/icon.png
electronVersion: 27.3.11
